### PR TITLE
Update to Ignition 8.1.24

### PR DESCRIPTION
**Pull request by etknorr**
* Updated Bake file to include Ignition 8.1.23 and 8.1.24
* Updated mes with latest urls and checksums
* Updated iiot with latest urls and checksums
* Updated Dockerfile to default to 8.1.24
* Minor updates to Readme to bump from 8.1.22 to 8.1.24

**Important Note**
It may appear that my wife updated the bake file. I assure you she did not. Just took me a little bit to change the user on her computer.

### CODE REVIEW

**Comment by etknorr** [comment]
@keith-gamble Let me know if there's anything that doesn't pass or that I can update.

**Review by keith-gamble — CHANGES_REQUESTED** [review]
Looks good, only issue is that you change the links and default build images for the secondary versions, but don't change the targets in the bake file. Basically you just want to find and replace `iiot-8-1-21` with `iiot-8-1-24` and `mes-8-1-20` with `mes-8-1-22`

**Review by keith-gamble — APPROVED** [review]
Actually I just made the changes for you

**Review by etknorr — COMMENTED** [review]
This was the thing you wanted me to do right? All my changes are there and the lint.yml also had the update you made.

**Pull request merged**
